[flake8]
exclude = .git, *migrations*, .tox, dist, htmlcov
max-line-length = 88
select = C,E,F,W,B,B950
ignore = E203, E231, E501, W503, W291, W293

[tox]
envlist = {py38, py39, py310, py311, py312}-django{42}, pylint

[testenv]
setenv =
    DJANGO_SETTINGS_MODULE = testauth.settings_aa4.local

deps=
    !django42: allianceauth<4
    django42: allianceauth>=4.0.0a4
    coverage
    factory_boy

commands_pre=
    pip list

commands=
    coverage run runtests.py mastery -v 2
    coverage xml
    coverage report

[testenv:pylint]
setenv =
    DJANGO_SETTINGS_MODULE = testauth.settings_aa4.local

deps=
    pylint
    pylint-django
    factory_boy
    allianceauth>=4.0.0a4
    aa-memberaudit>=4.3.1
    fittings>=2.3.0
    allianceauth-app-utils>=1.18
    django-esi>=8.3.1
    django-eveonline-sde>=0.0.1b2

commands=
    pylint --load-plugins pylint_django mastery