# Generated by Django 4.2.29 on 2026-04-19 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memberaudit', '0020_add_new_roles'),
        ('mastery', '0010_remove_fittingskilloverride'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillPlanProgression',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name of this learning progression (e.g., 'Basic Pilot Path')", max_length=255, unique=True, verbose_name='name')),
                ('description', models.TextField(blank=True, help_text='Description of the learning path and its purpose', verbose_name='description')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order in progression lists', verbose_name='order')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive progressions are hidden from pilot views', verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'skill plan progression',
                'verbose_name_plural': 'skill plan progressions',
                'ordering': ['order', 'name'],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='SkillPlanProgressionStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.CharField(help_text="Step identifier (e.g., '1', '2', '3a', '3b')", max_length=10, verbose_name='step number')),
                ('is_required', models.BooleanField(default=True, help_text='If False, this is an optional branch that pilots can choose instead of another', verbose_name='is required')),
                ('branch_key', models.CharField(blank=True, help_text="Group key for branching (e.g., 'step_3' groups 3a and 3b as alternatives)", max_length=50, null=True, verbose_name='branch key')),
                ('description', models.TextField(blank=True, help_text='Why this skillset is needed at this step', verbose_name='description')),
                ('order', models.PositiveIntegerField(help_text='Display order within the progression', verbose_name='order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'skill plan progression step',
                'verbose_name_plural': 'skill plan progression steps',
                'ordering': ['progression_id', 'order'],
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='skillplanprogressionstep',
            name='progression',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='mastery.skillplanprogression', verbose_name='progression'),
        ),
        migrations.AddField(
            model_name='skillplanprogressionstep',
            name='skillset_group',
            field=models.ForeignKey(help_text='The skillset group to learn at this step', on_delete=django.db.models.deletion.CASCADE, to='memberaudit.skillsetgroup', verbose_name='skillset group'),
        ),
        migrations.AlterUniqueTogether(
            name='skillplanprogressionstep',
            unique_together={('progression_id', 'skillset_group_id')},
        ),
    ]
