# Generated by Django 4.2.23 on 2026-05-02 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mastery", "0013_masterydoctrinereadinessfilter_alliances_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SdeCloneGradeSkill",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("max_alpha_level", models.IntegerField()),
                (
                    "skill_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="eve_sde.itemtype",
                    ),
                ),
            ],
            options={
                "indexes": [models.Index(fields=["max_alpha_level"], name="mastery_sde_max_al_63f970_idx")],
                "constraints": [
                    models.UniqueConstraint(fields=("skill_type",), name="mastery_unique_clone_grade_skill_type")
                ],
            },
        ),
    ]

